backend:
  name: git-gateway         # gebruikt Netlify Identity + Git Gateway
  branch: main              # jouw default branch

media_folder: "img/uploads" # waar geüploade plaatjes komen in de repo
public_folder: "/img/uploads"

site_url: "https://inquisitive-pie-5c49b6.netlify.app"

collections:
  - name: "projecten"
    label: "Projecten"
    folder: "projecten"     # elk item = één bestand in /projecten
    create: true
    slug: "{{slug}}"
    extension: "md"         # we bewaren als Markdown (veilig & simpel)
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Samenvatting", name: "summary", widget: "text", required: false }
      - { label: "Inhoud", name: "body", widget: "markdown" }
