backend:
  name: github
  repo: SimBeSim/klussenmetliefde
  branch: main
  base_url: "https://inquisitive-pie-5c49b6.netlify.app"
  auth_endpoint: "/api/auth"



publish_mode: editorial_workflow

media_folder: "img/uploads"
public_folder: "/img/uploads"

slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "projecten"
    label: "Projecten"
    folder: "projecten"
    create: true
    extension: "md"
    format: "frontmatter"
    identifier_field: "title"
    slug: "{{slug}}"
    sort: { field: "date", direction: "desc" }
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Samenvatting", name: "summary", widget: "text", required: false }
      - { label: "Categorie", name: "categorie", widget: "select", options: ["Tech","Manifest","Film","Maatschappij","Boek"], required: false }
      - { label: "Cover", name: "cover", widget: "image", required: false }
      - { label: "Inhoud", name: "body", widget: "markdown" }
